module.exports = [
  {
    name: 'national_population',
    type: 'value',
    namespace: 'national',
    format: ',',
    labels: [
      ['en', 'Population of Country'],
      ['es', 'Población del país'],
      ['id', 'Penduduk Negara'],
      ['pt', 'População do país'],
      ['fr', 'Population du pays']],
  },
  {
    name: 'national_gdp',
    type: 'value',
    namespace: 'national',
    subType: 'currency',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    isCurrency: true,
    labels: [
      ['en', 'Country GDP'],
      ['es', 'PIB del país'],
      ['id', 'PDB negara'],
      ['pt', 'País PIB'],
      ['fr', 'PIB du pays']],
  },
  {
    name: 'national_per_capita_income',
    type: 'value',
    namespace: 'national',
    subType: 'currency',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    isCurrency: true,
    labels: [
      ['en', 'Annual Per Capita Income'],
      ['es', 'Ingreso anual per cápita'],
      ['id', 'Pendapatan Per Kapita Tahunan'],
      ['pt', 'Renda anual per capita'],
      ['fr', 'Revenu annuel par habitant']],
  },
  {
    name: 'national_human_development_index',
    type: 'value',
    namespace: 'national',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 3,
      maximumFractionDigits: 3,
    },
    labels: [
      ['en', 'Human Development Index'],
      ['es', 'Índice de Desarrollo Humano'],
      ['id', 'Indeks Pembangunan Manusia'],
      ['pt', 'Índice de Desenvolvimento Humano'],
      ['fr', 'Indice de développement humain']],
  },
  {
    name: 'national_land_area',
    type: 'value',
    namespace: 'national',
    units: 'km²',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    labels: [
      ['en', 'Total Land Area'],
      ['es', 'Área total de la tierra'],
      ['id', 'Luas Tanah'],
      ['pt', 'Área de Terra Total'],
      ['fr', 'Superficie totale des terres']],
  },
  {
    name: 'national_percent_forested',
    type: 'value',
    namespace: 'national',
    units: '%',
    formatOptions: {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    labels: [
      ['en', '% Forest'],
      ['es', '% bosque'],
      ['id', '% Hutan'],
      ['pt', '% Floresta'],
      ['fr', '% Forêt']],
  },
  {
    name: 'deforestationTrend',
    type: 'value',
    namespace: 'national',
    subType: 'annual',
    labels: [
      ['en', 'Deforestation Trend'],
      ['es', 'Tendencia de deforestación'],
      ['id', 'Tren Deforestasi'],
      ['pt', 'Tendência do desmatamento'],
      ['fr', 'Tendance à la déforestation']],
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 1,
      maximumFractionDigits: 1,
    },
    units: '%',
    isDerived: true,
    get: (context) => {
      return context.calcTrend('array-national_deforestation_rate-national');
    },
  },

  {
    name: 'tons_of_co2_avoided',
    type: 'value',
    namespace: 'jurisdictional',
    subType: 'annual',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    units: 'tCO₂eq',
    labels: [
      ['en', 'Potential Annual CO₂ Avoided'],
      ['es', 'Potencial anual CO₂ Evitado'],
      ['id', 'CO₂ Annual Tahunan Potensial Dihindari'],
      ['pt', 'Potencial Anual de CO₂ Evitado'],
      ['fr', 'Potentiel annuel de CO₂ évité']],
  },
  {
    name: 'original_forest_area',
    type: 'value',
    namespace: 'jurisdictional',
    units: 'km²',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    labels: [
      ['en', 'Original Forest Area'],
      ['es', 'Área original del bosque'],
      ['id', 'Kawasan Hutan Asli'],
      ['pt', 'Área Florestal Original'],
      ['fr', 'Zone forestière originale']],
  },
  {
    name: 'land_area',
    type: 'value',
    namespace: 'jurisdictional',
    units: 'km²',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    labels: [
      ['en', 'Total Land Area'],
      ['es', 'Área total de la tierra'],
      ['id', 'Luas Tanah'],
      ['pt', 'Área de Terra Total'],
      ['fr', 'Superficie totale des terres']],
  },
  {
    name: 'forestArea',
    type: 'value',
    namespace: 'jurisdictional',
    units: 'km²',
    labels: [
      ['en', 'Current Forest Area'],
      ['es', 'Área actual del bosque'],
      ['id', 'Kawasan Hutan Saat Ini'],
      ['pt', 'Área florestal atual'],
      ['fr', 'Zone forestière actuelle']],
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
  },
  {
    name: 'forestCarbon',
    type: 'value',
    namespace: 'jurisdictional',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    units: 'M MtC',
    labels: [
      ['en', 'Total Forest Carbon'],
      ['es', 'Carbón forestal total'],
      ['id', 'Total Karbon Hutan'],
      ['pt', 'Carbono Florestal Total'],
      ['fr', 'Carbone forestier total']],
  },
  {
    name: 'population',
    type: 'value',
    namespace: 'jurisdictional',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    labels: [
      ['en', 'Population of State/Province'],
      ['es', 'Población del Estado / Provincia'],
      ['id', 'Penduduk Negara Bagian / Propinsi'],
      ['pt', 'População do Estado / Província'],
      ['fr', 'Population de l\'État / Province']],
  },
  {
    name: 'gdp',
    type: 'value',
    namespace: 'jurisdictional',
    subType: 'currency',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    labels: [
      ['en', 'State/Province GDP'],
      ['es', 'Estado / Provincia PIB'],
      ['id', 'PDB Negara Bagian / Provinsi'],
      ['pt', 'PIB estadual / provincial'],
      ['fr', 'État / Province PIB'],
    ],
  },
  {
    name: 'per_capita_income',
    type: 'value',
    namespace: 'jurisdictional',
    subType: 'currency',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    labels: [
      ['en', 'Annual Per Capita Income'],
      ['es', 'Ingreso anual per cápita'],
      ['id', 'Pendapatan Per Kapita Tahunan'],
      ['pt', 'Renda anual per capita'],
      ['fr', 'Revenu annuel par habitant'],
    ],
  },
  {
    name: 'human_development_index',
    type: 'value',
    namespace: 'jurisdictional',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 3,
      maximumFractionDigits: 3,
    },
    labels: [
      ['en', 'Human Development Index'],
      ['es', 'Índice de Desarrollo Humano'],
      ['id', 'Indeks Pembangunan Manusia'],
      ['pt', 'Índice de Desenvolvimento Humano'],
      ['fr', 'Indice de développement humain'],
    ],
  },
  {
    name: 'deforestationReferenceRate',
    type: 'value',
    namespace: 'jurisdictional',
    subType: 'annual',
    units: 'km²/yr',
    labels: [
      ['en', 'Deforestation Reference Rate'],
      ['es', 'Tasa de Referencia de Deforestación'],
      ['id', 'Laju Referensi Deforestasi'],
      ['pt', 'Taxa Referencial de Desmatamento'],
      ['fr', 'Taux de référence de la déforestation'],
    ],
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
  },
  {
    name: 'deforestation_reduction_goal',
    type: 'value',
    namespace: 'jurisdictional',
    subType: 'annual',
    units: 'km²/yr',
    labels: [
      ['en', 'Rio Branco Declaration Deforestation Reduction Goal'],
      ['es', 'Objetivo de reducción de la deforestación de la Declaración de Rio Branco'],
      ['id', 'Rio Branco Declaration Deforestation Reduction Goal'],
      ['pt', 'Meta da redução do desmatamento na Declaração de Rio Branco'],
      ['fr', 'Déclaration de Rio Branco Objectif de réduction de la déforestation'],
    ],
    footnotes: [
      ['en', 'These are the goals set forth in the Rio Branco Declaration provided that adequate, sufficient, and long-term performance-based funding is available'],
      ['es', 'Estos son los objetivos establecidos en la Declaración de Río Branco, siempre que se disponga de fondos adecuados, suficientes y basados en el rendimiento a largo plazo.'],
      ['id', 'Ini adalah tujuan yang ditetapkan dalam Deklarasi Rio Branco asalkan tersedia pendanaan berbasis kinerja yang memadai, cukup, dan jangka panjang'],
      ['pt', 'Essas são as metas estabelecidas na Declaração de Rio Branco, desde que haja financiamento adequado, suficiente e de longo prazo baseado no desempenho.'],
      ['fr', 'Ce sont les objectifs énoncés dans la Déclaration de Rio Branco à condition que des financements adéquats, suffisants et à long terme soient disponibles'],
    ],
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
  },
  {
    name: 'populationPercent',
    type: 'value',
    namespace: 'jurisdictional',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 1,
      maximumFractionDigits: 1,
    },
    units: '%',
    labels: [
      ['en', '% of National Population'],
      ['es', '% de la población nacional'],
      ['id', '% Penduduk Nasional'],
      ['pt', '% da população nacional'],
      ['fr', '% de la population nationale'],
    ],
    isDerived: true,
    get: (context) => {
      return context.calcPercent('value-population-jurisdictional', 'value-national_population-national');
    },
  },
  {
    name: 'currentForestAreaPercent',
    type: 'value',
    namespace: 'jurisdictional',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 1,
      maximumFractionDigits: 1,
    },
    units: '%',
    labels: [
      ['en', '% Forest'],
      ['es', '% Bosque'],
      ['id', '% Hutan'],
      ['pt', '% Floresta'],
      ['fr', '% Forêt'],
    ],
    isDerived: true,
    get: (context) => {
      return context.calcPercent('value-forestArea-jurisdictional', 'value-land_area-jurisdictional');
    },
  },
  {
    name: 'carbonPercentOfGlobal',
    type: 'value',
    namespace: 'jurisdictional',
    units: '%',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 3,
      maximumFractionDigits: 3,
    },
    labels: [
      ['en', '% of Global Total'],
      ['es', '% del total global'],
      ['id', '% dari Total Global'],
      ['pt', '% do Total Global'],
      ['fr', '% du total mondial'],
    ],
    isDerived: true,
    get: (context) => {
      return context.calcPercent('value-forestCarbon-jurisdictional', 'value-tropicalForestCarbonStocks-global');
    },
  },
  {
    name: 'forestAreaPercentOfGlobal',
    type: 'value',
    namespace: 'jurisdictional',
    units: '%',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 3,
      maximumFractionDigits: 3,
    },
    labels: [
      ['en', '% of Global Total'],
      ['es', '% del total global'],
      ['id', '% dari Total Global'],
      ['pt', '% do Total Global'],
      ['fr', '% du total mondial'],
    ],
    isDerived: true,
    get: (context) => {
      return context.calcPercent('value-forestArea-jurisdictional', 'value-tropicalForestArea-global');
    },
  },
  {
    name: 'landAreaPercentOfNation',
    type: 'value',
    namespace: 'jurisdictional',
    units: '%',
    isDerived: true,
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 1,
      maximumFractionDigits: 1,
    },
    labels: [
      ['en', ''],
      ['es', ''],
      ['id', ''],
      ['pt', ''],
    ],
  },
  {
    name: 'nationalPercentForested',
    type: 'value',
    namespace: 'national',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 1,
      maximumFractionDigits: 1,
    },
    units: '%',
    isDerived: true,
    labels: [
      ['en', ''],
      ['es', ''],
      ['id', ''],
      ['pt', ''],
    ],
  },
  {
    name: 'totalAreaDeforested',
    type: 'value',
    namespace: 'jurisdictional',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    units: 'km²',
    labels: [
      ['en', 'Total Area Deforested'],
      ['es', 'Área total deforestada'],
      ['id', 'Total Area yang terdebris'],
      ['pt', 'Área Total Desmatada'],
      ['fr', 'Superficie totale déboisée'],
    ],
    isDerived: true,
    get: (context) => {
      return context.calcDifference('value-original_forest_area-jurisdictional', 'value-forestArea-jurisdictional');
    },
  },
  {
    name: 'latestDeforestationRate',
    type: 'value',
    namespace: 'jurisdictional',
    subType: 'annual',
    units: 'km²',
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    isDerived: true,
    labels: [
      ['en', 'Deforestation Rate'],
      ['es', 'Tasa de deforestación'],
      ['id', 'laju deforestasi'],
      ['pt', 'Taxa de desmatamento'],
      ['fr', 'Taux de déforestation'],
    ],
  },
  {
    name: 'deforestationTrend',
    type: 'value',
    namespace: 'jurisdictional',
    subType: 'annual',
    units: '%',
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 1,
      maximumFractionDigits: 1,
    },
    isDerived: true,
    get: (context) => {
      return context.calcTrend('array-deforestation_rates-jurisdictional');
    },
    labels: [
      ['en', 'Deforestation Trend'],
      ['es', 'Tendencia de deforestación'],
      ['id', 'Tren Deforestasi'],
      ['pt', 'Tendência do desmatamento'],
      ['fr', 'Tendance à la déforestation'],
    ],
  }, {
    name: 'national_social_groups_percent',
    type: 'array',
    namespace: 'national',
    units: '%',
    labels: [
      ['en', 'Ethnic Groups'],
      ['es', 'Grupos étnicos'],
      ['id', 'Kelompok etnis'],
      ['pt', 'Grupos étnicos'],
      ['fr', 'Groupes ethniques'],
    ],
    isPercent: true,
    isSorted: true,
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    categoryLabels: [
      ['en', 'Group'],
      ['es', 'Grupo'],
      ['id', 'Kelompok'],
      ['pt', 'Grupo'],
      ['fr', 'Groupe'],
    ],
    rows: [
      ['a1', 'Multi-ethnic'],
      ['a2', 'White'],
      ['a3', 'Black'],
      ['a4', 'Indigenous'],
      ['a6', 'Other'],
    ],
    otherId: 'a6',
  },
  {
    name: 'national_urban_vs_rural_population_percent',
    type: 'array',
    namespace: 'national',
    categoryLabels: [
      ['en', 'Category'],
      ['es', 'Categoría'],
      ['id', 'Kategori'],
      ['pt', 'Categoria'],
      ['fr', 'Catégorie'],
    ],
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    units: '%',
    isSorted: true,
    isPercent: true,
    rows: [
      ['1', [
        ['en', 'Urban'],
        ['es', 'Urbana'],
        ['id', 'Urban'],
        ['pt', 'Urbana'],
        ['fr', 'Urbain']],
      ],
      ['2', [
        ['en', 'Rural'],
        ['es', 'Rural'],
        ['id', 'Pedesaan'],
        ['pt', 'Rural'],
        ['fr', 'Rural']],
      ],
    ],
    labels: [
      ['en', 'Urban vs. Rural Population'],
      ['es', 'Población urbana vs. rural'],
      ['id', 'Penduduk Urban vs. Pedesaan'],
      ['pt', 'População urbana versus rural'],
      ['fr', 'Population urbaine ou rurale'],
    ],
  },
  {
    name: 'national_gdp_breakdown_percent',
    type: 'array',
    namespace: 'national',
    categoryLabels: [
      ['en', 'Category'],
      ['es', 'Categoría'],
      ['id', 'Kategori'],
      ['pt', 'Categoria'],
      ['fr', 'Catégorie'],
    ],
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    units: '%',
    isSorted: true,
    isPercent: true,
    rows: [
      ['1', [
        ['en', 'Agriculture'],
        ['es', 'Agricultura'],
        ['id', 'Pertanian'],
        ['pt', 'Agricultura'],
        ['fr', 'Agriculture']],
      ],
      ['2', [
        ['en', 'Industry'],
        ['es', 'Industria'],
        ['id', 'Industri'],
        ['pt', 'Indústria'],
        ['fr', 'Industrie']],
      ],
      ['3', [
        ['en', 'Services'],
        ['es', 'Servicios'],
        ['id', 'Jasa'],
        ['pt', 'Serviços'],
        ['fr', 'Prestations de service']],
      ],
      ['4', [
        ['en', 'Forestry'],
        ['es', 'Silvicultura'],
        ['id', 'Kehutanan'],
        ['pt', 'Silvicultura'],
        ['fr', 'Sylviculture']],
      ],
      ['5', [
        ['en', 'Mining'],
        ['es', 'Minería'],
        ['id', 'Pertambangan'],
        ['pt', 'Mineração'],
        ['fr', 'Exploitation minière']],
      ],
    ],
    labels: [
      ['en', 'GDP Breakdown'],
      ['es', 'Desglose del PIB'],
      ['id', 'PDB'],
      ['pt', 'Desagregação do PIB'],
      ['fr', 'Répartition du PIB'],
    ],
  },
  {
    name: 'national_deforestation_rate',
    type: 'array',
    namespace: 'national',
    subType: 'annual',
    isSorted: false,
    labels: [
      ['en', 'Deforestation Rates'],
      ['es', 'Tasas de deforestación'],
      ['id', 'Tingkat Deforestasi'],
      ['pt', 'Taxas de desmatamento'],
      ['fr', 'Taux de déforestation'],
    ],
    categoryLabels: [
      ['en', 'Year'],
      ['es', 'Año'],
      ['id', 'Tahun'],
      ['pt', 'Año'],
      ['fr', 'Année'],
    ],
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    units: 'km²',
    rows: [
      ['2000', '2000'],
      ['2001', '2001'],
      ['2002', '2002'],
      ['2003', '2003'],
      ['2004', '2004'],
      ['2005', '2005'],
      ['2006', '2006'],
      ['2007', '2007'],
      ['2008', '2008'],
      ['2009', '2009'],
      ['2010', '2010'],
      ['2011', '2011'],
      ['2012', '2012'],
      ['2013', '2013'],
      ['2014', '2014'],
      ['2015', '2015'],
      ['2016', '2016'],
      ['2017', '2017'],
      ['2018', '2018'],
    ],
  },
  {
    name: 'deforestationReferenceRates',
    type: 'array',
    namespace: 'jurisdictional',
    subType: 'annual',
    isSorted: false,
    units: 'km²/yr',
    categoryLabels: [
      ['en', 'Year'],
      ['es', 'Año'],
      ['id', 'Tahun'],
      ['pt', 'Año'],
      ['fr', 'Année'],
    ],
    labels: [
      ['en', 'Deforestation Reference Rate'],
      ['es', 'Tasa de Referencia de Deforestación'],
      ['id', 'Laju Referensi Deforestasi'],
      ['pt', 'Taxa Referencial de Desmatamento'],
      ['fr', 'Taux de référence de la déforestation'],
    ],
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
  },
  {
    name: 'urban_vs_rural_population_percent',
    type: 'array',
    namespace: 'jurisdictional',
    categoryLabels: [
      ['en', 'Category'],
      ['es', 'Categoría'],
      ['id', 'Kategori'],
      ['pt', 'Categoria'],
      ['fr', 'Catégorie'],
    ],
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    units: '%',
    isSorted: true,
    isPercent: true,
    rows: [
      ['1', [
        ['en', 'Urban'],
        ['es', 'Urbana'],
        ['id', 'Urban'],
        ['pt', 'Urbana'],
        ['fr', 'Urbain']],
      ],
      ['2', [
        ['en', 'Rural'],
        ['es', 'Rural'],
        ['id', 'Pedesaan'],
        ['pt', 'Rural'],
        ['fr', 'Rural']],
      ],
    ],
    labels: [
      ['en', 'Urban vs. Rural Population'],
      ['es', 'Población urbana vs. rural'],
      ['id', 'Penduduk Urban vs. Pedesaan'],
      ['pt', 'População urbana versus rural'],
      ['fr', 'Population urbaine ou rurale'],
    ],
  },
  {
    name: 'social_groups_percent',
    type: 'array',
    namespace: 'jurisdictional',
    categoryLabels: [
      ['en', 'Group'],
      ['es', 'Grupo'],
      ['id', 'Kelompok'],
      ['pt', 'Grupo'],
      ['fr', 'Groupe'],
    ],
    labels: [
      ['en', 'Ethnic Groups'],
      ['es', 'Grupos étnicos'],
      ['id', 'Kelompok etnis'],
      ['pt', 'Grupos étnicos'],
      ['fr', 'Groupes ethniques'],
    ],
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    isSorted: true,
    isPercent: true,
    units: '%',
    rows: [
      ['a1', 'Multi-ethnic'],
      ['a2', 'White'],
      ['a3', 'Black'],
      ['a4', 'Indigenous'],
      ['a6', 'Other'],
    ],
    otherId: 'a6',
  },
  {
    name: 'gdp_breakdown_percent',
    type: 'array',
    namespace: 'jurisdictional',
    units: '%',
    isSorted: true,
    isPercent: true,
    labels: [
      ['en', 'GDP Breakdown'],
      ['es', 'Desglose del PIB'],
      ['id', 'PDB'],
      ['pt', 'Desagregação do PIB'],
      ['fr', 'Répartition du PIB'],
    ],
    categoryLabels: [
      ['en', 'Category'],
      ['es', 'Categoría'],
      ['id', 'Kategori'],
      ['pt', 'Categoria'],
      ['fr', 'Catégorie'],
    ],
    formatOptions: {
      minimumIntegerDigits: 1,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
    rows: [
      ['1', [
        ['en', 'Services'],
        ['es', 'Servicios'],
        ['id', 'Jasa'],
        ['pt', 'Serviços'],
        ['fr', 'Prestations de service']],
      ],
      ['2', [
        ['en', 'Agriculture'],
        ['es', 'Agricultura'],
        ['id', 'Pertanian'],
        ['pt', 'Agricultura'],
        ['fr', 'Agriculture']],
      ],
      ['3', [
        ['en', 'Forestry'],
        ['es', 'Silvicultura'],
        ['id', 'Kehutanan'],
        ['pt', 'Silvicultura'],
        ['fr', 'Sylviculture']],
      ],
      ['4', [
        ['en', 'Industry'],
        ['es', 'Industria'],
        ['id', 'Industri'],
        ['pt', 'Indústria'],
        ['fr', 'Industrie']],
      ],
      ['5', [
        ['en', 'Mining'],
        ['es', 'Minería'],
        ['id', 'Pertambangan'],
        ['pt', 'Mineração'],
        ['fr', 'Exploitation minière']],
      ],
    ],
  },
  {
    name: 'current_forest_area_typologies',
    type: 'array',
    namespace: 'jurisdictional',
    units: 'km²',
    isSorted: true,
    isPercent: true,
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    labels: [
      ['en', 'Major Vegetation Types'],
      ['es', 'Principales tipos de vegetación'],
      ['id', 'Jenis Vegetasi Utama'],
      ['pt', 'Tipos principais de vegetação'],
      ['fr', 'Types de végétation majeurs'],
    ],
    categoryLabels: [
      ['en', 'Category'],
      ['es', 'Categoría'],
      ['id', 'Kategori'],
      ['pt', 'Categoria'],
      ['fr', 'Catégorie'],
    ],
    rows: [
      ['1', [
        ['en', 'Upland Dense Humid Forest'],
        ['es', 'Upland Dense Bosque Húmedo'],
        ['id', 'Dataran Tinggi Hutan Dataran Tinggi'],
        ['pt', 'Floresta húmida densa Upland'],
        ['fr', 'Forêt humide dense d\'Upland']],
      ],
      ['2', [
        ['en', 'Floodplain Forest'],
        ['es', 'Bosque de la llanura de inundación'],
        ['id', 'Hutan Banjir'],
        ['pt', 'Floresta de planalto'],
        ['fr', 'Forêt inondable']],
      ],
      ['3', [
        ['en', 'Upland/Transition Dry Forest'],
        ['es', 'Upland / Transition Dry Forest'],
        ['id', 'Hutan Kering Dataran Tinggi / Transisi'],
        ['pt', 'Upland / Transition Dry Forest'],
        ['fr', 'Forêt sèche Upland / Transition']],
      ],
      ['4', [
        ['en', 'Savannah'],
        ['es', 'Sabana'],
        ['id', 'Savannah'],
        ['pt', 'Savana'],
        ['fr', 'Savane']],
      ],
      ['5', [
        ['en', 'Woodlands'],
        ['es', 'Bosques'],
        ['id', 'Woodlands'],
        ['pt', 'Woodlands'],
        ['fr', 'Woodlands']],
      ],
      ['6', [
        ['en', 'Peat Forest'],
        ['es', 'Bosque de turba'],
        ['id', 'Hutan Gambut'],
        ['pt', 'Floresta de turfa'],
        ['fr', 'Forêt de tourbe']],
      ],
      ['7', [
        ['en', 'Wetlands'],
        ['es', 'Humedales'],
        ['id', 'Lahan basah'],
        ['pt', 'Zonas húmidas'],
        ['fr', 'Zones humides']],
      ],
      ['8', [
        ['en', 'Mangroves'],
        ['es', 'Manglares'],
        ['id', 'Bakau'],
        ['pt', 'Manguezais'],
        ['fr', 'Mangroves']],
      ],
    ],
  },
  {
    name: 'forest_management',
    type: 'array',
    namespace: 'jurisdictional',
    categoryLabels: [
      ['en', 'Category'],
      ['es', 'Categoría'],
      ['id', 'Kategori'],
      ['pt', 'Categoria'],
      ['fr', 'Catégorie'],
    ],
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    units: 'km²',
    isSorted: true,
    isPercent: true,
    labels: [
      ['en', 'Forest Management'],
      ['es', 'Gestión de bosques'],
      ['id', 'Pengelolaan hutan'],
      ['pt', 'Gestão florestal'],
      ['fr', 'La gestion des forêts'],
    ],
  },
  {
    name: 'deforestation_rates',
    type: 'array',
    namespace: 'jurisdictional',
    subType: 'annual',
    isSorted: false,
    labels: [
      ['en', 'Deforestation Rates'],
      ['es', 'Tasas de deforestación'],
      ['id', 'Tingkat Deforestasi'],
      ['pt', 'Taxas de desmatamento'],
      ['fr', 'Taux de déforestation'],
    ],
    categoryLabels: [
      ['en', 'Year'],
      ['es', 'Año'],
      ['id', 'Tahun'],
      ['pt', 'Año'],
      ['fr', 'Année'],
    ],
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    units: 'km²',
    rows: [
      ['1996', '1996'],
      ['1997', '1997'],
      ['1998', '1998'],
      ['1999', '1999'],
      ['2000', '2000'],
      ['2001', '2001'],
      ['2002', '2002'],
      ['2003', '2003'],
      ['2004', '2004'],
      ['2005', '2005'],
      ['2006', '2006'],
      ['2007', '2007'],
      ['2008', '2008'],
      ['2009', '2009'],
      ['2010', '2010'],
      ['2011', '2011'],
      ['2012', '2012'],
      ['2013', '2013'],
      ['2014', '2014'],
      ['2015', '2015'],
      ['2016', '2016'],
      ['2017', '2017'],
      ['2018', '2018'],
    ],
  }, {
    name: 'governor',
    type: 'contact',
    subType: 'governor',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Governor'],
      ['es', 'Gobernador'],
      ['id', 'Gubernur'],
      ['pt', 'Governador'],
      ['fr', 'Gouverneur'],
    ],
  },
  {
    name: 'representative_1',
    type: 'contact',
    subType: 'representative',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Representative'],
      ['es', 'Representante'],
      ['id', 'Wakil'],
      ['pt', 'Representante'],
      ['fr', 'Représentant'],
    ],
  },
  {
    name: 'representative_2',
    type: 'contact',
    subType: 'representative',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Representative'],
      ['es', 'Representante'],
      ['id', 'Wakil'],
      ['pt', 'Representante'],
      ['fr', 'Représentant'],
    ],
  }, {
    name: 'national_main_exports',
    type: 'text',
    namespace: 'national',
    labels: [
      ['en', 'Main Exports'],
      ['es', 'Exportaciones principales'],
      ['id', 'Ekspor utama'],
      ['pt', 'Principais exportações'],
      ['fr', 'Principales exportations'],
    ],
  },
  {
    name: 'txt_state_description',
    type: 'text',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Description'],
      ['es', 'Descripción'],
      ['id', 'Deskripsi'],
      ['pt', 'Descrição'],
      ['fr', 'La description'],
    ],
  },
  {
    name: 'main_exports',
    type: 'text',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Main Exports'],
      ['es', 'Exportaciones principales'],
      ['id', 'Ekspor utama'],
      ['pt', 'Principais exportações'],
      ['fr', 'Principales exportations'],
    ],
  },
  {
    name: 'txt_causes_of_deforestation',
    type: 'text',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Drivers of Deforestation'],
      ['es', 'Impulsores de la deforestación'],
      ['id', 'Pengemudi Deforestasi'],
      ['pt', 'Drivers of Deforestation'],
      ['fr', 'Les moteurs de la déforestation'],
    ],
  },
  {
    name: 'overviewForestMonitoringAndMeasurementSystems',
    type: 'text',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Overview of Forest Monitoring and Measurement Systems'],
      ['es', 'Descripción general de los sistemas de monitoreo y medición forestal'],
      ['id', 'Ikhtisar Sistem Monitoring dan Pengukuran Hutan'],
      ['pt', 'Visão geral dos sistemas de monitoramento e medição florestal'],
      ['fr', 'Aperçu des systèmes de surveillance et de mesure des forêts'],
    ],
  }, {
    name: 'txt_laws',
    type: 'framework',
    namespace: 'national',
    labels: [
      ['en', 'Laws'],
      ['es', 'Leyes'],
      ['id', 'Hukum'],
      ['pt', 'Leis'],
      ['fr', 'Lois'],
    ],
  },
  {
    name: 'txt_policies_and_plans',
    type: 'framework',
    namespace: 'national',
    labels: [
      ['en', 'Policies and Plans'],
      ['es', 'Políticas y planes'],
      ['id', 'Kebijakan dan Rencana'],
      ['pt', 'Políticas e planos'],
      ['fr', 'Politiques et plans'],
    ],
  },
  {
    name: 'txt_institutions',
    type: 'framework',
    namespace: 'national',
    labels: [
      ['en', 'Institutions'],
      ['es', 'Instituciones'],
      ['id', 'Institusi'],
      ['pt', 'Instituições'],
      ['fr', 'Institutions'],
    ],
  },
  {
    name: 'frameworksLawsPoliciesStrategies',
    type: 'framework',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Laws, Policies and Strategies'],
      ['es', 'Leyes, políticas y estrategias'],
      ['id', 'Hukum, Kebijakan dan Strategi'],
      ['pt', 'Leis, políticas e estratégias'],
      ['fr', 'Lois, politiques et stratégies'],
    ],
  },
  {
    name: 'frameworksInstitutionalFramework',
    type: 'framework',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Institutional Framework'],
      ['es', 'Marco institucional'],
      ['id', 'Kerangka kelembagaan'],
      ['pt', 'Estrutura institucional'],
      ['fr', 'Cadre institutionnel'],
    ],
  },
  {
    name: 'frameworksZoningSpatialPlanning',
    type: 'framework',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Zoning and Spatial Planning'],
      ['es', 'Zonificación y planificación espacial'],
      ['id', 'Perencanaan Zonasi dan Tata Ruang'],
      ['pt', 'Zoneamento e Ordenamento do Território'],
      ['fr', 'Zonage et aménagement du territoire'],
    ],
  },
  {
    name: 'frameworksSafeguards',
    type: 'framework',
    namespace: 'jurisdictional',
    labels: [
      ['en', 'Engagement and Participation with Indigenous Peoples and Local Communities'],
      ['es', 'Compromiso y participación con los pueblos indígenas y las comunidades locales'],
      ['id', 'Keterlibatan dan Partisipasi dengan Masyarakat Adat dan Komunitas Lokal'],
      ['pt', 'Engajamento e Participação com Povos Indígenas e Comunidades Locais'],
      ['fr', 'Engagement et participation avec les peuples autochtones et les communautés locales'],
    ],
  },
];
