
'use strict';

module.exports = [
  {
    name: 'social_groups_percent',
    type: 'array',
    units: '', /* per client: Peru jurisdictions are listed by actual population rather than percent */
    formatOptions: {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    },
    rows: [
      ['u2018-2', 'Achuar'],
      ['u2018-3', 'Aguaruna (Aguajun)'],
      ['u2018-4', 'Amahuaca'],
      ['u2018-5', 'Amarakaeri'],
      ['u2018-6', 'Amuesha (Yanesha)'],
      ['u2018-7', 'Arazaeri'],
      ['u2018-8', 'Asheninka'],
      ['u2018-9', 'Awajun'],
      ['u2018-10', 'Cashibo-Cacataibo'],
      ['u2018-11', 'Cashinahua'],
      ['u2018-12', 'Chayahuita'],
      ['u2018-13', 'Cocama-Cocamilla'],
      ['u2018-14', 'Culina'],
      ['u2018-15', 'Ese’ejja'],
      ['u2018-16', 'Huachipaeri'],
      ['u2018-17', 'Huambisa'],
      ['u2018-18', 'Kichwaruna'],
      ['u2018-19', 'Kisamberi-Sapitieri-Amarakaeri'],
      ['u2018-20', 'Kukama - kukamiria'],
      ['u2018-1', 'Lamas (Llacuash)'],
      ['u2018-21', 'Marinahua'],
      ['u2018-22', 'Mastanahua-Sharanahua-Marinahua'],
      ['u2018-23', 'Matsiguenga'],
      ['u2018-24', 'Other'],
      ['u2018-25', 'Piro'],
      ['u2018-26', 'Pukirieri'],
      ['u2018-27', 'Quechua'],
      ['u2018-28', 'Sharanahua-Marinahua'],
      ['u2018-29', 'Shipibo-Conibo'],
      ['u2018-30', 'Toyoeri-Amahuaca-Matsiguenga'],
      ['u2018-31', 'Toyoeri-Shipibo-Conibo-Ese’ejja-Arazaeri-Matsiguenga'],
      ['u2018-32', 'Yaminahua'],
    ],
    otherId: 'u2018-24',
  },
  {
    name: 'gdp_breakdown_percent',
    type: 'array',
    rows: [
      ['u2018-4',
        [
          ['en', 'Agriculture, Livestock, Hunting and Forestry'],
          ['es', 'Agricultura, Ganadería, Caza y Silvicultura'],
        ],
      ],
      ['u2018-5',
        [
          ['en', 'Building'],
          ['es', 'Construcción'],
        ],
      ],
      ['u2018-2',
        [
          ['en', 'Commerce'],
          ['es', 'Comercio'],
        ],
      ],
      ['u2018-3',
        [
          ['en', 'Manufacturing'],
          ['es', 'Manufactura'],
        ],
      ],
      ['u2018-8',
        [
          ['en', 'Oil and Mining'],
          ['es', 'Petroleo y minería'],
        ],
      ],
      ['u2018-6',
        [
          ['en', 'Other sectors'],
          ['es', 'Otros sectores'],
        ],
      ],
      ['u2018-1',
        [
          ['en', 'Other service sectors'],
          ['es', 'Otros Servicios'],
        ],
      ],
      ['u2018-7',
        [
          ['en', 'Public Administration and Defense'],
          ['es', 'Administración pública y defensa'],
        ],
      ],
    ],
    otherId: 'u2018-6',
  },
  {
    name: 'current_forest_area_typologies',
    type: 'array',
    rows: [
      ['u2018-3',
        [
          ['en', 'Aguajal / Palmeral'],
          ['es', 'Aguajal / Palmeral'],
        ],
      ],
      ['u2018-4',
        [
          ['en', 'Aguajales'],
          ['es', 'Aguajales'],
        ],
      ],
      ['u2018-1',
        [
          ['en', 'Andean agriculture'],
          ['es', 'Agricultura andina'],
        ],
      ],
      ['u2018-16',
        [
          ['en', 'Andean forests with medium and large trees in high mountains'],
          ['es', 'Bosques andinos con árboles medianos y grandes en montañas altas'],
        ],
      ],
      ['u2018-30',
        [
          ['en', 'Arboreal swamp communities (renacales and palm groves)'],
          ['es', 'Comunidades pantanosas arbóreas (renacales y palmerales)'],
        ],
      ],
      ['u2018-22',
        [
          ['en', 'Dense semi-deciduous forests in hills'],
          ['es', 'Bosques semicaducifolios densos en colinas'],
        ],
      ],
      ['u2018-23',
        [
          ['en', 'Dense semi-deciduous forests in plains'],
          ['es', 'Bosques semicaducifolios densos en planicies'],
        ],
      ],
      ['u2018-21',
        [
          ['en', 'Dense sub-Andean forests with large and medium trees in low hills'],
          ['es', 'Bosques densos subandinos con árboles grandes y medianos en colinas bajas'],
        ],
      ],
      ['u2018-15',
        [
          ['en', 'Dry forest'],
          ['es', 'Bosque seco'],
        ],
      ],
      ['u2018-31',
        [
          ['en', 'Dry scrub'],
          ['es', 'Matorral seco'],
        ],
      ],
      ['u2018-14',
        [
          ['en', 'Flooded forest'],
          ['es', 'Bosque inundados'],
        ],
      ],
      ['u2018-17',
        [
          ['en', 'Forests with medium-sized trees of low mountains, eastern sub-Andean'],
          ['es', 'Bosques con árboles medianos de montañas bajas subandinas oriental'],
        ],
      ],
      ['u2018-36',
        [
          ['en', 'High terrace'],
          ['es', 'Terraza alta'],
        ],
      ],
      ['u2018-18',
        [
          ['en', 'Hill forests'],
          ['es', 'Bosques de la colina'],
        ],
      ],
      ['u2018-7',
        [
          ['en', 'Humid  High Hills Forests'],
          ['es', 'Bosque Húmedo de Colinas Altas'],
        ],
      ],
      ['u2018-11',
        [
          ['en', 'Humid Forest of High Terraces'],
          ['es', 'Bosque Húmedo de Terrazas Altas'],
        ],
      ],
      ['u2018-12',
        [
          ['en', 'Humid Forest of Low Terraces'],
          ['es', 'Bosque húmedo de Terrazas Bajas'],
        ],
      ],
      ['u2018-8',
        [
          ['en', 'Humid low hills Forests'],
          ['es', 'Bosque Húmedo de Colinas Bajas'],
        ],
      ],
      ['u2018-10',
        [
          ['en', 'Humid Mountain Forest'],
          ['es', 'Bosque Húmedo de Montaña'],
        ],
      ],
      ['u2018-2',
        [
          ['en', 'Intensive agriculture'],
          ['es', 'Agricultura intensiva'],
        ],
      ],
      ['u2018-5',
        [
          ['en', 'Intervening Areas'],
          ['es', 'Áreas Intervenidas'],
        ],
      ],
      ['u2018-37',
        [
          ['en', 'Low terrace'],
          ['es', 'Terraza baja'],
        ],
      ],
      ['u2018-38',
        [
          ['en', 'Medium terrace'],
          ['es', 'Terraza media'],
        ],
      ],
      ['u2018-26',
        [
          ['en', 'Middle Hill'],
          ['es', 'Colina media'],
        ],
      ],
      ['u2018-28',
        [
          ['en', 'Mixed communities of bamboos, or mixed pacales, associated with scattered trees in hills'],
          ['es', 'Comunidades mixtas de bambúes, o pacales mixtos, asociados con árboles dispersos en colinas'],
        ],
      ],
      ['u2018-29',
        [
          ['en', 'Mixed communities of bamboos, or mixed pacales, associated with scattered trees in plains'],
          ['es', 'Comunidades mixtas de bambúes, o pacales mixtos, asociados con árboles dispersos en planicies'],
        ],
      ],
      ['u2018-9',
        [
          ['en', 'Moist Forest of Mendric Plains'],
          ['es', 'Bosque Húmedo de Llanura Meándricas'],
        ],
      ],
      ['u2018-32',
        [
          ['en', 'Montana'],
          ['es', 'Montaña'],
        ],
      ],
      ['u2018-19',
        [
          ['en', 'Mountain forests'],
          ['es', 'Bosques de montaña'],
        ],
      ],
      ['u2018-35',
        [
          ['en', 'Natural grass'],
          ['es', 'Pasto natural'],
        ],
      ],
      ['u2018-6',
        [
          ['en', 'Non-forested areas'],
          ['es', 'Áreas no boscosas'],
        ],
      ],
      ['u2018-33',
        [
          ['en', 'Others'],
          ['es', 'Others'],
        ],
      ],
      ['u2018-27',
        [
          ['en', 'Riverside complex'],
          ['es', 'Complejo de orillares'],
        ],
      ],
      ['u2018-25',
        [
          ['en', 'Sub-Andean forests of steep high mountains'],
          ['es', 'Bosques subandinos de montañas altas empinadas'],
        ],
      ],
      ['u2018-24',
        [
          ['en', 'Sub-Andean forests with medium and large trees in low mountains'],
          ['es', 'Bosques subandinos con árboles medianos y grandes en montañas bajas'],
        ],
      ],
      ['u2018-34',
        [
          ['en', 'Swamps'],
          ['es', 'Pantanos'],
        ],
      ],
      ['u2018-20',
        [
          ['en', 'Terraced forests'],
          ['es', 'Bosques de terrazas'],
        ],
      ],
      ['u2018-13',
        [
          ['en', 'Wet Forest of Terraces Stockings'],
          ['es', 'Bosque Húmedo de Terrazas Medias'],
        ],
      ],
    ],
    otherId: 'u2018-33',
  },
  {
    name: 'forest_management',
    type: 'array',
    rows: [
      ['u2018-1',
        [
          ['en', 'Areas of Environmental Conservation - ACA'],
          ['es', 'Áreas Naturales Protegidas Nacionales'],
        ],
      ],
      ['u2018-10',
        [
          ['en', 'Concessions for conservation'],
          ['es', 'Concesiones para conservación'],
        ],
      ],
      ['u2018-11',
        [
          ['en', 'Concessions for Forestation and Reforestation'],
          ['es', 'Concesiones para Forestación y Reforestación'],
        ],
      ],
      ['u2018-7',
        [
          ['en', 'Ecotourism concessions'],
          ['es', 'Concesiones de ecoturismo'],
        ],
      ],
      ['u2018-13',
        [
          ['en', 'Indigenous Reserves'],
          ['es', 'Reservas Indígenas'],
        ],
      ],
      ['u2018-4',
        [
          ['en', 'National Protected Areas'],
          ['es', 'Áreas de Conservación Regional'],
        ],
      ],
      ['u2018-6',
        [
          ['en', 'Native titled communities'],
          ['es', 'Comunidades nativas tituladas'],
        ],
      ],
      ['u2018-9',
        [
          ['en', 'Non-timber forest concessions'],
          ['es', 'Concesiones forestales no maderables'],
        ],
      ],
      ['u2018-12',
        [
          ['en', 'Other forest concessions'],
          ['es', 'Otras concesiones forestales'],
        ],
      ],
      ['u2018-5',
        [
          ['en', 'Peasant communities'],
          ['es', 'Comunidades campesinas'],
        ],
      ],
      ['u2018-2',
        [
          ['en', 'Private Conservation Areas - ACP'],
          ['es', 'Äreas de Conservación Ambiental  - ACA'],
        ],
      ],
      ['u2018-16',
        [
          ['en', 'Private lands'],
          ['es', 'Tierras privadas'],
        ],
      ],
      ['u2018-15',
        [
          ['en', 'Ramsar site'],
          ['es', 'Sitio Ramsar'],
        ],
      ],
      ['u2018-3',
        [
          ['en', 'Regional Conservation Areas'],
          ['es', 'Áreas de Conservación Privada – ACP'],
        ],
      ],
      ['u2018-8',
        [
          ['en', 'Timber forest concessions'],
          ['es', 'Concesiones forestales maderables'],
        ],
      ],
      ['u2018-14',
        [
          ['en', 'Without defined tenure or other types of tenure without available data'],
          ['es', 'Sin tenencia definida u otros tipos de tenencia sin data disponible'],
        ],
      ],
    ],
  },

];
