
'use strict';

module.exports = [
  {
    name: 'social_groups_percent',
    type: 'array',
    rows: [
      ['u2018-1', 'Amuzgos'],
      ['u2018-2', 'Black'],
      ['u2018-3', 'Chatinos'],
      ['u2018-4', 'Chinantecos'],
      ['u2018-5', 'Chochos'],
      ['u2018-6', 'Chol'],
      ['u2018-7', 'Chontales'],
      ['u2018-8', 'Cuicatecos'],
      ['u2018-9', 'Huaves'],
      ['u2018-10', 'Indigenous'],
      ['u2018-11', 'Kanjobal'],
      ['u2018-12', 'Mame'],
      ['u2018-13', 'Maya'],
      ['u2018-14', 'Mazatecos'],
      ['u2018-15', 'Mestizo'],
      ['u2018-16', 'Mixes'],
      ['u2018-17', 'Mixtecos'],
      ['u2018-18', 'Multi-ethnic'],
      ['u2018-19', 'Nahuas'],
      ['u2018-20',
        [
          ['en', 'Other'],
          ['es', 'Otro'],
          ['id', 'Lain'],
          ['pt', 'De outros'],
        ],
      ],
      ['u2018-21', 'Tojolabales'],
      ['u2018-22', 'Triquis'],
      ['u2018-23', 'Tzeltal'],
      ['u2018-24', 'Tzotzil'],
      ['u2018-25', 'White'],
      ['u2018-26', 'Zapotecos'],
      ['u2018-27', 'Zoques'],
    ],
    otherId: 'u2018-20',
  },
  {
    name: 'gdp_breakdown_percent',
    type: 'array',
    rows: [
      ['a1',
        [
          ['en', 'Agriculture, Forestry'],
          ['es', 'Agricultura, Silvicultura'],
          ['id', 'Pertanian, Kehutanan'],
          ['pt', 'Agricultura, silvicultura'],
        ],
      ],
      ['u2018-3', 'Construction'],
      ['u2018-4', 'Government Activities'],
      ['a2',
        [
          ['en', 'Industry, Mining'],
          ['es', 'Industria, Minería'],
          ['id', 'Industri, Pertambangan'],
          ['pt', 'Indústria, Mineração'],
        ],
      ],
      ['u2018-1', 'Manufacturing Industry'],
      ['u2018-5',
        [
          ['en', 'Other'],
          ['es', 'Otro'],
          ['id', 'Lain'],
          ['pt', 'De outros'],
        ],
      ],
      ['a3',
        [
          ['en', 'Services'],
          ['es', 'Servicios'],
          ['id', 'Jasa'],
          ['pt', 'Serviços'],
        ],
      ],
      ['u2018-2', 'Trade'],
    ],
    otherId: 'u2018-5',
  },
  {
    name: 'current_forest_area_typologies',
    type: 'array',
    rows: [
      ['u2017a',
        [
          ['en', 'Conifer Forest Primary'],
          ['es', 'Bosque primario de coníferas'],
          ['id', 'Hutan Primer Konifer'],
          ['pt', 'Conifer Forest Primary'],
        ],
      ],
      ['u2018m',
        [
          ['en', 'Other'],
          ['es', 'Otro'],
          ['id', 'Lain'],
          ['pt', 'De outros'],
        ],
      ],
      ['u2017d',
        [
          ['en', 'Primary Deciduous'],
          ['es', 'Primitivo de hoja caduca'],
          ['id', 'Dasar surut'],
          ['pt', 'Decídua primária'],
        ],
      ],
      ['u2017b',
        [
          ['en', 'Primary Encino Forest'],
          ['es', 'Bosque primario de Encino'],
          ['id', 'Hutan Encino Utama'],
          ['pt', 'Floresta encino primária'],
        ],
      ],
      ['u2017c',
        [
          ['en', 'Primary Mesophytic Forest'],
          ['es', 'Bosque mesofítico primario'],
          ['id', 'Hutan Mesofitik primer'],
          ['pt', 'Floresta mesofítica primária'],
        ],
      ],
      ['u2017e',
        [
          ['en', 'Primary Perrenial'],
          ['es', 'Perrenial primario'],
          ['id', 'Perrenial Primer'],
          ['pt', 'Perrenial primário'],
        ],
      ],
      ['u2017g',
        [
          ['en', 'Secondary Coniferous'],
          ['es', 'Conífero secundario'],
          ['id', 'Konifer sekunder'],
          ['pt', 'Conífera secundária'],
        ],
      ],
      ['u2017j',
        [
          ['en', 'Secondary Deciduous'],
          ['es', 'Secundario Deciduo'],
          ['id', 'Secondary Deciduous'],
          ['pt', 'Secundária Deciduous'],
        ],
      ],
      ['u2017h',
        [
          ['en', 'Secondary Encino Forest'],
          ['es', 'Bosque secundario de Encino'],
          ['id', 'Hutan Encino Sekunder'],
          ['pt', 'Floresta Encino Secundária'],
        ],
      ],
      ['u2017i',
        [
          ['en', 'Secondary Mesophytic Foresty'],
          ['es', 'Selva mesofítica secundaria'],
          ['id', 'Hutan Mesofitik sekunder'],
          ['pt', 'Floresto Mesofítico Secundário'],
        ],
      ],
      ['u2017k',
        [
          ['en', 'Secondary Perennial Forest'],
          ['es', 'Bosque perenne secundario'],
          ['id', 'Hutan Perennial Sekunder'],
          ['pt', 'Floresta perene secundária'],
        ],
      ],
      ['u2017f',
        [
          ['en', 'Secondary Sub-deciduous Forest'],
          ['es', 'Bosque subcaducto secundario'],
          ['id', 'Hutan sub-deciduous sekunder'],
          ['pt', 'Floresta Secundária Sub-decídua'],
        ],
      ],
      ['u2017l',
        [
          ['en', 'Secondary Sub-deciduous Jungle'],
          ['es', 'Selva Sub-decidua Secundaria'],
          ['id', 'Hutan Sub-deciduous Sekunder'],
          ['pt', 'Junção Secundária Sub-deciduous'],
        ],
      ],
    ],
    otherId: 'u2018m',
  },
  {
    name: 'forest_management',
    type: 'array',
    rows: [
      ['u2017a',
        [
          ['en', 'Ejido'],
          ['es', 'Ejido'],
          ['id', 'Ejido'],
          ['pt', 'Ejido'],
        ],
      ],
      ['u2017b',
        [
          ['en', 'Protected Area'],
          ['es', 'Área protegida'],
          ['id', 'Kawasan Lindung'],
          ['pt', 'Área protegida'],
        ],
      ],
      ['u2017c',
        [
          ['en', 'Other'],
          ['es', 'Otro'],
          ['id', 'Lain'],
          ['pt', 'De outros'],
        ],
      ],
    ],
    otherId: 'u2017c',
  },
];
