
'use strict';

module.exports = [
  {
    name: 'social_groups_percent',
    type: 'array',
    rows: [
      ['a1', 'Efik'],
      ['a2', 'Ekoi'],
      ['a3', 'Ejagham'],
      ['a4', 'Bako'],
      ['a5', 'Bete'],
      ['a6', 'Boki'],
      ['a7', 'Mbembe'],
      ['a8', 'Other'],
    ],
  },
  {
    name: 'gdp_breakdown_percent',
    type: 'array',
    rows: [
      ['1',
        [
          ['en', 'Services'],
          ['es', 'Servicios'],
          ['id', 'Jasa'],
          ['pt', 'Serviços'],
        ],
      ],
      ['2',
        [
          ['en', 'Agriculture'],
          ['es', 'Agricultura'],
          ['id', 'Pertanian'],
          ['pt', 'Agricultura'],
        ],
      ],
      ['3',
        [
          ['en', 'Forestry'],
          ['es', 'Silvicultura'],
          ['id', 'Kehutanan'],
          ['pt', 'Silvicultura'],
        ],
      ],
      ['4',
        [
          ['en', 'Industry'],
          ['es', 'Industria'],
          ['id', 'Industri'],
          ['pt', 'Indústria'],
        ],
      ],
      ['5',
        [
          ['en', 'Mining'],
          ['es', 'Minería'],
          ['id', 'Pertambangan'],
          ['pt', 'Mineração'],
        ],
      ],
    ],
  },
  {
    name: 'current_forest_area_typologies',
    type: 'array',
    rows: [
      ['u2017a',
        [
          ['en', 'Settlement'],
          ['es', 'Asentamiento'],
          ['id', 'Penyelesaian'],
          ['pt', 'Assentamento'],
        ],
      ],
      ['u2017b',
        [
          ['en', 'Oil palm, Rubber'],
          ['es', 'Palma de aceite, caucho'],
          ['id', 'Kelapa sawit, karet'],
          ['pt', 'Palma de óleo, borracha'],
        ],
      ],
      ['u2017c',
        [
          ['en', 'Farmland'],
          ['es', 'Tierras de cultivo'],
          ['id', 'Tanah pertanian'],
          ['pt', 'Terras agrícolas'],
        ],
      ],
      ['u2017d',
        [
          ['en', 'Tropical High Forest'],
          ['es', 'Bosque tropical alto'],
          ['id', 'Hutan Tinggi Tropis'],
          ['pt', 'Floresta tropical alta'],
        ],
      ],
      ['u2017e',
        [
          ['en', 'Open Forest'],
          ['es', 'Bosque abierto'],
          ['id', 'Hutan Terbuka'],
          ['pt', 'Floresta aberta'],
        ],
      ],
      ['u2017f',
        [
          ['en', 'Montane Forest'],
          ['es', 'Bosque montano'],
          ['id', 'Hutan Montane'],
          ['pt', 'Montane Forest'],
        ],
      ],
      ['u2017g',
        [
          ['en', 'Gmelina'],
          ['es', 'Gmelina'],
          ['id', 'Gmelina'],
          ['pt', 'Gmelina'],
        ],
      ],
      ['u2017h',
        [
          ['en', 'Derived Savannah'],
          ['es', 'Sabana derivada'],
          ['id', 'Berasal dari Savannah'],
          ['pt', 'Savana derivada'],
        ],
      ],
      ['u2017i',
        [
          ['en', 'Grazing Field'],
          ['es', 'Campo de pastoreo'],
          ['id', 'Lapangan penggembalaan'],
          ['pt', 'Campo de pastagem'],
        ],
      ],
      ['u2017j',
        [
          ['en', 'Mangrove'],
          ['es', 'Mangle'],
          ['id', 'Bakau'],
          ['pt', 'Mangue'],
        ],
      ],
      ['u2017k',
        [
          ['en', 'Swamp'],
          ['es', 'Pantano'],
          ['id', 'Rawa'],
          ['pt', 'Pântano'],
        ],
      ],
      ['u2017l',
        [
          ['en', 'Waterbody'],
          ['es', 'Agua corporal'],
          ['id', 'Waterbody'],
          ['pt', 'Corpo d\'água'],
        ],
      ],
    ],
  },
  {
    name: 'forest_management',
    type: 'array',
    rows: [
      ['management_national',
        [
          ['en', 'National Conservation Areas'],
          ['es', 'Áreas Nacionales de Conservación'],
          ['id', 'Kawasan Konservasi Nasional'],
          ['pt', 'Áreas nacionais de conservação'],
        ],
      ],
      ['management_state',
        [
          ['en', 'State Forest Reserves'],
          ['es', 'Reservas forestales estatales'],
          ['id', 'Cadangan Hutan Negara'],
          ['pt', 'Reservas Florestais Estaduais'],
        ],
      ],
      ['management_community',
        [
          ['en', 'Community Forest Estates'],
          ['es', 'Comunidad Forest Estates'],
          ['id', 'Perkebunan Hutan Rakyat'],
          ['pt', 'Community Forest Estates'],
        ],
      ],
    ],
  },

];
